# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


fibonacci = [1, 2]

while fibonacci[-1] < 4000000:
    next_fib = fibonacci[-1] + fibonacci[-2]
    if next_fib < 4000000:
        fibonacci.append(next_fib)
    else:
        break

print(fibonacci)

def sum_even_numbers(list):
    even_numbers = []
    for x in list:
        if x%2 == 0:
            even_numbers.append(x)
    print('even numbers sum:', sum(even_numbers))

sum_even_numbers(fibonacci)